version: '3'
services:
  postgres:
    image: postgres:11-alpine
    container_name: "my_postgres"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  main-service:
    image: openjdk:8-jre-alpine
    build: https://github.com/rifkiansyahmc/main-eureka.git
    volumes:
      - ./main:/tmp/main
    ports:
      - "8101:8101"
    depends_on:
      - postgres

  sales-service:
    image: openjdk:8-jre-alpine
    build: https://github.com/rifkiansyahmc/sales.git
    volumes:
      - ./sales:/tmp/sales
    ports:
      - "8100:8100"
    depends_on:
      - postgres
      - main-service


  inventory-service:
    image: openjdk:8-jre-alpine
    build: https://github.com/rifkiansyahmc/inventory.git
    volumes:
      - ./inventory:/tmp/inventory
    ports:
      - "8102:8102"
    depends_on:
      - postgres
      - main-service


  partner-service:
    image: openjdk:8-jre-alpine
    build: https://github.com/rifkiansyahmc/partner-service.git
    volumes:
      - ./partner:/tmp/partner
    ports:
      - "8103:8103"
    depends_on:
      - postgres
      - main-service


volumes:
  my_dbdata: